### ISSUE TITLE
Does esa-climate-toolbox require matplotlib or just matplotlib-base?

### ISSUE THREAD

**Issue by pont-us** [esa-cci/esa-climate-toolbox#16]
@TonioF `matplotlib` was recently added to `environment.yml`, but this also pulls in the whole pyqt stack -- see note [here](https://conda-forge.org/docs/maintainer/knowledge_base/#matplotlib). Do we actually need that, or would `matplotlib-base` be sufficient?

**Comment by TonioF** [comment]
It was not necessary. It has been changed.
